### ISSUE TITLE
Criar roadmap geral

### ISSUE THREAD

**Issue by lucianaribeiro** [fga-eps-mds/2019.1-Gaia#139]
Nessa issue será realizado:
- [ ] Criar roadmap do projeto
- [ ] Inserir todas as sprints até a R1

Critérios de aceitação:
- [ ] Estar documentado na wiki

**Comment by lucianaribeiro** [comment]
Estava na Sprint 5 porque foi entregue para a R1 (que foi no início da semana), porém ocorreu na Sprint 6, esse é o motivo da mudança da milestone.
