### ISSUE TITLE
Criar roadmap de cada frente

### ISSUE THREAD

**Issue by lucianaribeiro** [fga-eps-mds/2019.1-Gaia#15]
Nessa issue será realizado:
- [x] DevOps deve criar o seu roadmap para a primeira release 
- [x] Architecture Owner deve criar o seu roadmap para a primeira release
- [x] Product Owner deve criar o seu roadmap para a primeira release  
- [x] Tech Lead deve criar o seu roadmap para a primeira release 

Critérios de aceitação:
- [x] Estar documentado na wiki
- [x] Cada papel com sua cor de acordo com a paleta de cores do projeto
- [x] Todas as sprints da R1 preenchidas
