### ISSUE TITLE
Refatorar roadmap dos papeis

### ISSUE THREAD

**Issue by lucianaribeiro** [fga-eps-mds/2019.1-Gaia#157]
Nessa issue será realizado:
- [x] Refatorar roadmap da arquiteta
- [x] Refatorar roadmap do devops
- [x] Refatorar roadmap da product owner
- [x] Refatorar roadmap da tech leader

Critérios de aceitação:
- [x] Estar documentado na wiki.
